FROM node:18

WORKDIR /app

# Обов’язково копіюємо також package-lock.json
COPY package.json package-lock.json ./
COPY tsconfig.json ./

# Використовуємо npm ci для production-білду
RUN npm ci

COPY src/ ./src/

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
